version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8081:5000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=password
    networks:
      - app_network
    container_name: 2023MCS320009_web

  worker:
    build: ./worker
    depends_on:
      - redis
    networks:
      - app_network
    container_name: 2023MCS320009_worker

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - app_network
    container_name: 2023MCS320009_db

  redis:
    image: redis:latest
    networks:
      - app_network
    container_name: 2023MCS320009_redis

networks:
  app_network:

volumes:
  db_data:
